"""create initial tables

Revision ID: 17b152fac61b
Revises:
Create Date: 2026-03-11 09:18:41.763856

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "17b152fac61b"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "teas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_teas_id"), "teas", ["id"], unique=False)
    op.create_table(
        "tea_variants",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tea_id", sa.Integer(), nullable=False),
        sa.Column(
            "packaging_type",
            sa.Enum("foil", "wing", "gift", name="packaging_type"),
            nullable=False,
        ),
        sa.Column("unit", sa.Enum("grams", "bags", name="unit"), nullable=False),
        sa.Column(
            "flush", sa.Enum("first", "second", name="flush_type"), nullable=False
        ),
        sa.Column("harvest_year", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["tea_id"],
            ["teas.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tea_variants_id"), "tea_variants", ["id"], unique=False)
    op.create_table(
        "stock_transactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tea_variant_id", sa.Integer(), nullable=False),
        sa.Column("quantity_change", sa.Integer(), nullable=False),
        sa.Column(
            "transaction_type",
            sa.Enum(
                "sale",
                "donation",
                "ceremony",
                "damaged",
                "convert",
                "harvest",
                name="transaction_type",
            ),
            nullable=False,
        ),
        sa.Column("performed_by_id", sa.UUID(), nullable=False),
        sa.Column("performed_by_name", sa.String(), nullable=False),
        sa.Column("buyer_name", sa.String(), nullable=True),
        sa.Column("buyer_phone", sa.String(), nullable=True),
        sa.Column(
            "sales_channel",
            sa.Enum("online", "offline", name="sales_channel_type"),
            nullable=True,
        ),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["tea_variant_id"],
            ["tea_variants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_stock_transactions_id"), "stock_transactions", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_stock_transactions_id"), table_name="stock_transactions")
    op.drop_table("stock_transactions")
    op.drop_index(op.f("ix_tea_variants_id"), table_name="tea_variants")
    op.drop_table("tea_variants")
    op.drop_index(op.f("ix_teas_id"), table_name="teas")
    op.drop_table("teas")
    # ### end Alembic commands ###
